# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.gui = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update system
    pacman -Syu --noconfirm
    
    # Install Python for Ansible
    pacman -S --noconfirm python python-pip
  SHELL
end